DURHAM_WELCOME_MESSAGE: " Inspiring people to do outstanding things"
DURHAM_PRIMARY_COLOR: "#68246d" # purple

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# DURHAM_FOOTER_NAV_LINKS: []
# DURHAM_FOOTER_LEGAL_LINKS: []
DURHAM_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"
DURHAM_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "/tos"
